Больше деталей
htmlacademy-univer-javascript-1/2433129-kekstagram-4 pull request #5
Opened 2023-10-16 14:06 UTC by ConquestSucks

2023-10-19 10:39 UTC, MaksimovG requested changes

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +  const comments = [];
сразу внутри объекта надо записать. Description не по тз вычисляется

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +];
название не по критериям

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +const usedCommentId = [];
зачем эта переменная в корне файла

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +  const objects = [];
невнятное название

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +const generateList = () => {
ошибки линтера (неиспользуемая функция)

2023-10-19 10:39 UTC, MaksimovG commented on js/main.js
> +};
в общем мой совет посмотреть лекцию

2023-10-19 11:42 UTC, ConquestSucks commented on js/main.js
> +];
Имена авторов также должны быть случайными. Набор имён для комментаторов составьте сами. Подставляйте случайное имя в поле name.

2023-10-19 11:42 UTC, ConquestSucks commented on js/main.js
> +const usedCommentId = [];
Чтобы потом проверять, использовался ли данный id

2023-10-19 11:43 UTC, ConquestSucks commented on js/main.js
> +  const comments = [];
? description, строка — описание фотографии. Описание придумайте самостоятельно.

2023-10-20 10:14 UTC, MaksimovG requested changes

2023-10-20 10:14 UTC, MaksimovG commented on js/main.js
> +};
C большой буквы. Перечитываем критерии

2023-10-20 10:14 UTC, MaksimovG commented on js/main.js
> +const generateListOfObjects = () => Array.from({ length: 25 }, getPost);
25 магическое число

2023-10-20 10:14 UTC, MaksimovG commented on js/main.js
> +const generateListOfObjects = () => Array.from({ length: 25 }, getPost);
дать говорящее название, это слишком абстарктное

2023-10-22 11:39 UTC, MaksimovG requested changes

2023-10-22 11:39 UTC, MaksimovG commented on js/main.js
> +};
PhotoIdv LikeCount - перечитываем критерии. Как назваются перечисления в частности

2023-10-22 12:23 UTC, merged